title: 33. TaCoS
description: > # this means to ignore newlines until "baseurl:"
  33. TaCoS Conference in Saarbr√ºcken
baseurl: "" # the subpath of your site, e.g. /blog
url: "tacosconference.github.io/" # th  e base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2024_style/img/tacos_2024_logo_circle.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

#include: ['_2016_pages', '_2017_pages']

include: ['_2024_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: facebook
  #  url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com/tacosconference
  - title: instagram
    url: https://www.instagram.com/tacosconference/

incremental: true
permalink: pretty
# Source: "G:/My Drive/UdS/TaCoS/tacosConference.github.io"
Server address: http://127.0.0.1:4000/
regenerate: true